# Generated by Django 3.1.3 on 2020-11-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name1',
            field=models.CharField(default='a', max_length=40),
        ),
    ]
