# Generated by Django 3.1.1 on 2020-10-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201010_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Associate', 'Associate'), ('Employee', 'Employee')], default='Employer', max_length=10),
        ),
    ]
