# Generated by Django 3.1.1 on 2020-10-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201010_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
