# Generated by Django 3.1.1 on 2020-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.CharField(max_length=100),
        ),
    ]
