# Generated by Django 3.1.1 on 2020-10-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_professions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professions',
            new_name='Diplomas',
        ),
        migrations.AlterModelTable(
            name='diplomas',
            table='all_diplomas',
        ),
    ]
