# Generated by Django 3.1.1 on 2020-10-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201011_1306'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diplomas',
        ),
    ]
