# Generated by Django 3.1.1 on 2020-10-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='formation',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
