# Generated by Django 3.1.1 on 2020-10-13 06:52

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}),
        ),
    ]
