# Generated by Django 3.1.1 on 2020-10-13 07:52

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20201013_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'geocoder': False}),
        ),
    ]
