# Generated by Django 3.1.1 on 2020-10-13 07:58

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20201013_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={}, verbose_name={'center': [46.71101751719283, 2.793591348463309]}),
        ),
    ]
