# Generated by Django 3.1.1 on 2020-10-13 07:59

from django.db import migrations
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20201013_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [46.71101751719283, 2.793591348463309]}),
        ),
    ]
