# Generated by Django 3.1.1 on 2020-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20201013_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='none', upload_to=''),
            preserve_default=False,
        ),
    ]
