# Generated by Django 3.1.1 on 2020-10-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20201013_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='curriculum_vitae',
            field=models.FileField(null=True, upload_to='media/curriculums/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='media/profile_pics/'),
        ),
    ]
