# Generated by Django 3.1.1 on 2020-10-14 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20201014_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='curriculum_vitae',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
