# Generated by Django 3.1.1 on 2020-10-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20201014_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contrat',
            field=models.CharField(default='', max_length=50),
        ),
    ]
