# Generated by Django 3.1.1 on 2020-10-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20201014_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Employer', 'Un employé'), ('Associate', 'Un associé'), ('Employee', 'Un employeur')], default='Employee', max_length=10),
        ),
    ]
