# Generated by Django 3.1.1 on 2020-10-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20201014_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='diplome',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
