# Generated by Django 3.1.1 on 2020-10-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_customuser_diplome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='diplome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='formation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
