# Generated by Django 3.1.1 on 2020-10-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20201017_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contrat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
