# Generated by Django 3.1.1 on 2020-10-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20201019_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_company',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
